# Generated by Django 4.1 on 2024-04-26 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=20)),
                ("building_name", models.CharField(max_length=20)),
                ("addr_num", models.IntegerField()),
                ("addr_street", models.CharField(max_length=20)),
                ("addr_city", models.CharField(max_length=20)),
                ("addr_state", models.CharField(max_length=5)),
                ("addr_zipcode", models.CharField(max_length=5)),
                ("year_built", models.PositiveIntegerField()),
            ],
            options={
                "unique_together": {("company_name", "building_name")},
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_name", models.CharField(max_length=50)),
                ("pet_type", models.CharField(max_length=50)),
                ("pet_size", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "unique_together": {("pet_name", "pet_type", "user")},
            },
        ),
    ]
