# Generated by Django 4.1 on 2024-04-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApartmentBuilding",
        ),
        migrations.AlterUniqueTogether(
            name="pet",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="pet",
            constraint=models.UniqueConstraint(
                fields=("pet_name", "pet_type", "user_id"), name="pet"
            ),
        ),
    ]
