# Generated by Django 4.1 on 2024-04-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_delete_apartmentbuilding_alter_pet_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=20)),
                ("building_name", models.CharField(max_length=20)),
                ("addr_num", models.IntegerField()),
                ("addr_street", models.CharField(max_length=20)),
                ("addr_city", models.CharField(max_length=20)),
                ("addr_state", models.CharField(max_length=5)),
                ("addr_zipcode", models.CharField(max_length=5)),
                ("year_built", models.PositiveIntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="apartmentbuilding",
            constraint=models.UniqueConstraint(
                fields=("company_name", "building_name"), name="apartment_building"
            ),
        ),
    ]
