# Generated by Django 4.1 on 2024-04-26 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_apartmentbuilding_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentUnit",
            fields=[
                ("unit_rent_id", models.AutoField(primary_key=True, serialize=False)),
                ("unit_number", models.CharField(max_length=10)),
                ("monthly_rent", models.IntegerField()),
                ("square_footage", models.IntegerField()),
                ("available_date_for_move_in", models.DateField()),
                (
                    "apartment_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.apartmentbuilding",
                    ),
                ),
            ],
        ),
    ]
