# Generated by Django 4.1 on 2024-04-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_apartmentunit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("square_footage", models.IntegerField()),
                ("description", models.CharField(max_length=50)),
                (
                    "unit_rent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.apartmentunit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="rooms",
            constraint=models.UniqueConstraint(
                fields=("name", "unit_rent_id"), name="room"
            ),
        ),
    ]
