# Generated by Django 4.1 on 2024-04-26 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rooms_rooms_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_type", models.CharField(max_length=50)),
                ("pet_size", models.CharField(max_length=20)),
                ("is_allowed", models.BooleanField()),
                ("registration_fee", models.IntegerField(blank=True, null=True)),
                ("monthly_fee", models.IntegerField(blank=True, null=True)),
                (
                    "apartment_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.apartmentbuilding",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="petpolicy",
            constraint=models.UniqueConstraint(
                fields=("pet_type", "pet_size", "apartment_building"), name="pet_policy"
            ),
        ),
    ]
