# Generated by Django 4.1 on 2024-04-26 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0006_petpolicy_petpolicy_pet_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenities",
            fields=[
                (
                    "atype",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Provides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=20)),
                ("building_name", models.CharField(max_length=20)),
                ("fee", models.IntegerField()),
                ("waiting_list", models.IntegerField()),
                (
                    "apartment_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.apartmentbuilding",
                    ),
                ),
                (
                    "atype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.amenities"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roommate_cnt", models.PositiveSmallIntegerField()),
                ("move_in_date", models.DateField()),
                (
                    "unit_rent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.apartmentunit",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AmenitiesIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.amenities"
                    ),
                ),
                (
                    "unit_rent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.apartmentunit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="provides",
            constraint=models.UniqueConstraint(
                fields=("atype", "apartment_building"), name="provide"
            ),
        ),
        migrations.AddConstraint(
            model_name="interests",
            constraint=models.UniqueConstraint(
                fields=("username", "unit_rent_id"), name="interest"
            ),
        ),
        migrations.AddConstraint(
            model_name="amenitiesin",
            constraint=models.UniqueConstraint(
                fields=("atype", "unit_rent_id"), name="amenities_in"
            ),
        ),
    ]
